# Generated by Django 3.2.3 on 2021-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='csv_ready_to_wix',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
